### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Chookyin** [XiaoXinYo/Bing-Chat#1]
[2023-03-01 17:38:04,618] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1890, in ensure_sync
    return self.async_to_sync(func)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1911, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1890, in ensure_sync
    return self.async_to_sync(func)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1911, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gevent/pywsgi.py", line 999, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.9/dist-packages/gevent/pywsgi.py", line 945, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1727, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
  File "/www/wwwroot/Bing-Chat/bing_chat_api.py", line 60, in errorhandler_500
    return GenerateResponseResult.error(500, '未知错误')
TypeError: error() missing 1 required positional argument: 'message'
2023-03-01T17:38:04Z {'REMOTE_ADDR': '39.144.160.12', 'REMOTE_PORT': '19995', 'HTTP_HOST': 'x.x.x.x:xxx', (hidden keys: 25)} failed with TypeError

39.144.160.12 - - [2023-03-01 17:38:04] "POST / HTTP/1.1" 500 161 0.007573

**Comment by ykaiqx** [comment]
尝试安装flask[async]
`pip3 install "flask[async]"`

**Comment by Chookyin** [comment]
> 尝试安装flask[async]
> `pip3 install "flask[async]"`

使用venv虚拟环境后依然报错，是否为cookie格式错误？

**Comment by ykaiqx** [comment]
我正在用fastapi框架写，请稍等

**Comment by ykaiqx** [comment]
查看新版本
https://github.com/XiaoXinYo/Bing-Chat/commit/e9a45229be0f9642d9df0924159b1767a5cb281b

**Comment by Chookyin** [comment]
```
RuntimeError: You cannot use AsyncToSync in the same thread as an async event loop - just await the async function directly.
```
python3.9是否不符合版本？

**Comment by ykaiqx** [comment]
你用的是最新的bing_chat吗？

python 3.9是支持的

**Comment by Chookyin** [comment]
是最新的，刚刚使用venv虚拟环境安装的，新git之后还是报错
![A2933E7E-75E3-4753-8ABB-027CF777A372](https://user-images.githubusercontent.com/77994706/222356031-37ccad67-36dc-406c-8bd0-6e78c37bfb58.jpeg)

**Comment by ykaiqx** [comment]
使用最新的源码，并安装python-multipart库，即可解决。上个版本我没测试post，不好意思哈。

**Comment by Chookyin** [comment]
安装之后还是不行，状态码500，内部错误。
![F8487232-C1AB-4022-B407-1674F579FF07](https://user-images.githubusercontent.com/77994706/222367752-b6d9f0fa-79ae-40f3-a24b-d8fdebbdc545.jpeg)

**Comment by ykaiqx** [comment]
查看你的cookie.json内容是否完整

**Comment by Chookyin** [comment]
> 

恢复快照，重置cookie，新git已解决，非常感谢
