### ISSUE TITLE
返回  “格式错误”

### ISSUE THREAD

**Issue by faithmq** [XiaoXinYo/Bing-Chat#13]
Faith-Mac ： ~/Downloads/Bing-Chat-main：sudo python3 ./bing_chat.py
Password:
INFO:     Started server process [35578]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 63299) - "WebSocket /ws_stream" [accepted]
INFO:     connection open
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/user/Downloads/Bing-Chat-main/./bing_chat.py", line 113, in wsStream
    parameters = await ws.receive_json()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1005

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 238, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/opt/homebrew/lib/python3.11/site-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/Users/user/Downloads/Bing-Chat-main/./bing_chat.py", line 168, in wsStream
    await ws.send_text(GenerateResponse().error(500, '未知错误', True))
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/websockets.py", line 163, in send_text
    await self.send({"type": "websocket.send", "text": data})
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/websockets.py", line 85, in send
    await self._send(message)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in sender
    await send(message)
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 329, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.send', after sending 'websocket.close'.
INFO:     connection closed

**Comment by ykaiqx** [comment]
如果你是使用websocket方式连接，客户端需要以json格式发送，例如
`{"style": "balanced", "question": "你好"}`

**Comment by faithmq** [comment]
您好，我是使用文档内自带的example目录下的web.html链接的  该如何修改呢？ 请教~

**Comment by faithmq** [comment]
理解了，可是为啥不直接把自带的搜索框格式改成对应的呢，小白摸索半天，终于用你给的代码粘到搜索框里实现了发送。感谢！

**Comment by ykaiqx** [comment]
忘改了，稍等。

**Comment by faithmq** [comment]
正在摸索能接入飞书机器人的代码，不知道大佬后期会不会出类似的教程。https://github.com/bestony/ChatGPT-Feishu

**Comment by ykaiqx** [comment]
可以做，但是如果 问题复杂，回答时间会很长。这个不像ChatGPT有官方提供的接口（响应快）。

**Comment by ykaiqx** [comment]
> 忘改了，稍等。

已更新

**Comment by faithmq** [comment]
> 可以做，但是如果 问题复杂，回答时间会很长。这个不像ChatGPT有官方提供的接口（响应快）。
那个Chatgpt作者飞书群有一千多号人啦，对这个有需求的企业客户应该不在少数。

**Comment by ykaiqx** [comment]
问一些常规的问题，可能要等待30s以上，因为要等待bing。
