### ISSUE TITLE
启动出现错误

### ISSUE THREAD

**Issue by MartinZiYun** [XiaoXinYo/Bing-Chat#17]
`Traceback (most recent call last):
  File "bing_chat.py", line 53, in <module>
    def getStyleEnum(style: str) -> EdgeGPT.ConversationStyle:
AttributeError: module 'EdgeGPT' has no attribute 'ConversationStyle'`

**Comment by ykaiqx** [comment]
讲edgegpt库，更新至，0.0.55以上



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MartinZiYun ***@***.***&gt;
发送时间: 2023年3月10日 21:16
收件人: XiaoXinYo/Bing-Chat ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[XiaoXinYo/Bing-Chat] 启动出现错误 (Issue #17)





 
Traceback (most recent call last): File "bing_chat.py", line 53, in <module&gt; def getStyleEnum(style: str) -&gt; EdgeGPT.ConversationStyle: AttributeError: module 'EdgeGPT' has no attribute 'ConversationStyle'

**Comment by MartinZiYun** [comment]
好的谢谢！
